# See https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled

enabled: true

exclude:
  - "**/*.patch"
  - "**/node_modules/**/*"
  - "**/vendor/**/*"
  - ".github/workflows/**/*" # https://github.com/restyled-io/restyler/issues/73

changed_paths:
  maximum: 1000
  outcome: error

remote_files: []

auto: false

commit_template: |
  Restyled by ${restyler.name}
pull_requests: true

comments: true

statuses:
  skipped: true
  differences: true
  no_differences: true
  error: true

request_review: author

labels: ["Restyle"]

ignore_authors:
  - "*[bot]"

ignore_branches:
  - "renovate/*"

ignore_labels:
  - restyled-ignore

restylers_version: stable

restylers:
  - name: isort
    image: 'restyled/restyler-isort:v5.9.3'
    command:
      - isort
    arguments: []
    include:
      - '**/*.py'
    interpreters:
      - python
  - name: black
    image: 'restyled/restyler-black:v20.8b1'
    command:
      - black
    arguments: [ ]
    include:
      - '**/*.py'
    interpreters:
      - python
